import { useState, useEffect, useCallback } from 'react'
import './TopStories.css'

/**
 * TopStories — Editorial "Top Stories Today" section.
 *
 * Surfaces the top 3 financial stories of the day with summaries,
 * presented in a hero + supporting layout. Fetches from Google News RSS
 * via rss2json proxy. Falls back to curated financial source links.
 */

const TOP_STORIES_FEED =
  'https://news.google.com/rss/search?q=global+economy+stocks+markets+interest+rates&hl=en-AU&gl=AU&ceid=AU:en'

const ASX_FEED =
  'https://news.google.com/rss/search?q=ASX+Australian+stock+market&hl=en-AU&gl=AU&ceid=AU:en'

const RSS_PROXY = 'https://api.rss2json.com/v1/api.json?rss_url='

function timeAgo(dateStr) {
  if (!dateStr) return ''
  try {
    const d = new Date(dateStr)
    const now = new Date()
    const diff = Math.floor((now - d) / 1000)
    if (diff < 60) return 'just now'
    if (diff < 3600) return `${Math.floor(diff / 60)}m ago`
    if (diff < 86400) return `${Math.floor(diff / 3600)}h ago`
    if (diff < 604800) return `${Math.floor(diff / 86400)}d ago`
    return d.toLocaleDateString('en-AU', { day: 'numeric', month: 'short' })
  } catch {
    return ''
  }
}

function cleanTitle(title) {
  return title.replace(/\s*[-–—]\s*[^-–—]+$/, '').trim()
}

function cleanDescription(html) {
  if (!html) return ''
  // Strip HTML tags, decode entities, clean up whitespace
  const text = html
    .replace(/<[^>]*>/g, '')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\s+/g, ' ')
    .trim()
  // Truncate to ~250 chars at sentence boundary
  if (text.length <= 250) return text
  const truncated = text.slice(0, 250)
  const lastPeriod = truncated.lastIndexOf('.')
  if (lastPeriod > 120) return truncated.slice(0, lastPeriod + 1)
  return truncated + '…'
}

const FALLBACK_STORIES = [
  {
    title: 'Global Markets Rally on Economic Optimism',
    url: 'https://www.reuters.com/markets/',
    source: 'Reuters',
    sourceIcon: '🌐',
    pubDate: new Date().toISOString(),
    summary: 'Global equity markets are trading higher amid improving economic sentiment. Investors are weighing central bank policy signals against strong corporate earnings data, with tech and financial sectors leading gains across major indices.',
    category: 'Markets',
  },
  {
    title: 'ASX Tracks Wall Street Gains Overnight',
    url: 'https://www.afr.com/markets',
    source: 'AFR',
    sourceIcon: '🇦🇺',
    pubDate: new Date().toISOString(),
    summary: 'The Australian share market is positioned to open higher, tracking positive moves on Wall Street. Mining and banking stocks are in focus as commodity prices stabilize.',
    category: 'ASX',
  },
  {
    title: 'Central Banks Signal Policy Path Forward',
    url: 'https://www.cnbc.com/world-markets/',
    source: 'CNBC',
    sourceIcon: '📺',
    pubDate: new Date().toISOString(),
    summary: 'Central banks globally continue to navigate the balance between inflation control and economic growth, with bond markets closely watching for any changes in forward guidance.',
    category: 'Economy',
  },
]

export default function TopStories({ className = '' }) {
  const [stories, setStories] = useState([])
  const [loading, setLoading] = useState(true)
  const [lastUpdated, setLastUpdated] = useState(null)

  const fetchTopStories = useCallback(async () => {
    // Phase 1: Try pre-cached daily stories (generated by CI/CD)
    try {
      const cachedRes = await fetch('/data/top_stories.json')
      if (cachedRes.ok) {
        const cached = await cachedRes.json()
        if (cached.topStories?.length >= 2) {
          // Check if cache is fresh (< 26 hours for timezone slack)
          const generatedAt = cached.generatedAt ? new Date(cached.generatedAt) : null
          const ageHours = generatedAt ? (Date.now() - generatedAt.getTime()) / (1000 * 60 * 60) : 999
          if (ageHours < 26) {
            setStories(cached.topStories.slice(0, 3).map(s => ({
              ...s,
              sourceIcon: s.sourceIcon || '🌐',
            })))
            setLastUpdated(cached.generatedAt)
            setLoading(false)
            return // Fresh cache — skip live fetch
          }
        }
      }
    } catch {
      // Cache miss or parse error — fall through to live fetch
    }

    try {
      // Fallback: live fetch from Google News RSS
      const [globalRes, asxRes] = await Promise.allSettled([
        fetch(`${RSS_PROXY}${encodeURIComponent(TOP_STORIES_FEED)}`),
        fetch(`${RSS_PROXY}${encodeURIComponent(ASX_FEED)}`),
      ])

      const allItems = []

      for (const result of [globalRes, asxRes]) {
        if (result.status === 'fulfilled' && result.value.ok) {
          const data = await result.value.json()
          if (data.status === 'ok' && data.items) {
            allItems.push(...data.items)
          }
        }
      }

      if (allItems.length === 0) {
        setStories(FALLBACK_STORIES)
        setLoading(false)
        return
      }

      // Deduplicate and pick top stories
      const seen = new Set()
      const deduped = allItems
        .sort((a, b) => new Date(b.pubDate) - new Date(a.pubDate))
        .filter(item => {
          const key = item.title?.toLowerCase().slice(0, 40)
          if (!key || seen.has(key)) return false
          seen.add(key)
          return true
        })

      // Map to clean stories with summaries
      const topStories = deduped.slice(0, 3).map(item => ({
        title: cleanTitle(item.title),
        url: item.link,
        source: item.author || 'Reuters',
        sourceIcon: item.author?.includes('CNBC') ? '📺' :
                     item.author?.includes('AFR') || item.author?.includes('Australia') ? '🇦🇺' :
                     item.author?.includes('Bloomberg') ? '💹' :
                     item.author?.includes('MarketWatch') ? '📊' : '🌐',
        pubDate: item.pubDate,
        summary: cleanDescription(item.description) ||
                 'Read the full story for market insights, analysis, and the latest economic data.',
        category: item.author?.includes('ASX') || item.author?.includes('Australia') ? 'ASX' :
                  item.author?.includes('economy') ? 'Economy' : 'Markets',
      }))

      setStories(topStories.length >= 2 ? topStories : FALLBACK_STORIES)
    } catch {
      setStories(FALLBACK_STORIES)
    }
    setLoading(false)
  }, [])

  useEffect(() => {
    fetchTopStories()
    // Re-check every 30 minutes (cached file rarely changes, but live might)
    const interval = setInterval(fetchTopStories, 30 * 60 * 1000)
    return () => clearInterval(interval)
  }, [fetchTopStories])

  if (loading) {
    return (
      <div className={`top-stories ${className}`} id="top-stories">
        <div className="top-stories__header">
          <div className="top-stories__label">
            <span className="top-stories__label-icon">📰</span>
            <span className="top-stories__label-text">Top Stories Today</span>
            <span className="top-stories__live">
              <span className="top-stories__live-dot" />
              Live
            </span>
          </div>
        </div>
        <div className="top-stories__grid">
          <div className="top-stories__skeleton top-stories__skeleton--hero" />
          <div className="top-stories__skeleton-pair">
            <div className="top-stories__skeleton top-stories__skeleton--card" />
            <div className="top-stories__skeleton top-stories__skeleton--card" />
          </div>
        </div>
      </div>
    )
  }

  const hero = stories[0]
  const supporting = stories.slice(1, 3)

  return (
    <div className={`top-stories ${className}`} id="top-stories">
      <div className="top-stories__header">
        <div className="top-stories__label">
          <span className="top-stories__label-icon">📰</span>
          <span className="top-stories__label-text">Top Stories Today</span>
          <span className="top-stories__live">
            <span className="top-stories__live-dot" />
            Live
          </span>
        </div>
        <p className="top-stories__subtitle">
          Today's most important financial and economic stories, summarised
        </p>
      </div>

      <div className="top-stories__grid">
        {/* Hero story — largest, most prominent */}
        {hero && (
          <a
            href={hero.url}
            target="_blank"
            rel="noopener noreferrer"
            className="top-stories__hero"
          >
            <div className="top-stories__hero-gradient" />
            <div className="top-stories__hero-content">
              <div className="top-stories__hero-meta">
                <span className="top-stories__hero-source">
                  {hero.sourceIcon} {hero.source}
                </span>
                <span className="top-stories__hero-time">{timeAgo(hero.pubDate)}</span>
              </div>
              <h2 className="top-stories__hero-title">{hero.title}</h2>
              <p className="top-stories__hero-summary">{hero.summary}</p>
              <div className="top-stories__hero-footer">
                <span className="top-stories__hero-category">{hero.category}</span>
                <span className="top-stories__hero-cta">
                  Read full story
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                    <line x1="7" y1="17" x2="17" y2="7" />
                    <polyline points="7 7 17 7 17 17" />
                  </svg>
                </span>
              </div>
            </div>
          </a>
        )}

        {/* Supporting stories */}
        {supporting.length > 0 && (
          <div className="top-stories__supporting">
            {supporting.map((story, i) => (
              <a
                key={`${story.title}-${i}`}
                href={story.url}
                target="_blank"
                rel="noopener noreferrer"
                className="top-stories__card"
              >
                <div className="top-stories__card-meta">
                  <span className="top-stories__card-source">
                    {story.sourceIcon} {story.source}
                  </span>
                  <span className="top-stories__card-time">{timeAgo(story.pubDate)}</span>
                </div>
                <h3 className="top-stories__card-title">{story.title}</h3>
                <p className="top-stories__card-summary">{story.summary}</p>
                <div className="top-stories__card-footer">
                  <span className="top-stories__card-category">{story.category}</span>
                  <span className="top-stories__card-cta">
                    Read more →
                  </span>
                </div>
              </a>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}
